Ejemplo simple con una sola red neuronal

In [1]:
import numpy as np

In [2]:
# cargamos las 4 combinaciones de las compuertas XOR
training_data = np.array([[0,0],[0,1],[1,1],[1,0],[0,0],[0,1],[1,1],[1,0],[0,0],[0,1],[1,1],[1,0],
                          [0,0],[0,1],[1,1],[1,0],[0,0],[0,1],[1,1],[1,0],[0,0],[0,1],[1,1],[1,0]], "float32")

In [3]:
# y estos son los resultados que se obtienen, en el mismo orden
#target_data = np.array([[0],[3],[3],[3],[0],[3],[3],[3],[0],[3],[3],[3],
#                        [0],[3],[3],[3],[0],[3],[3],[3],[0],[3],[3],[3]], "float32")
target_data = np.array([[0],[1],[1],[1],[0],[1],[1],[1],[0],[1],[1],[1],
                        [0],[1],[1],[1],[0],[1],[1],[1],[0],[1],[1],[1]], "float32")

In [4]:
from sklearn.linear_model import Perceptron
clf_Perceptron = Perceptron()
clf_Perceptron.fit(training_data, target_data)

C:\Users\joseg\.conda\envs\datascience\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [5]:
y_pred = clf_Perceptron.predict(training_data)

In [6]:
from sklearn.metrics import accuracy_score
accuracy_score(target_data, y_pred)

1.0

In [7]:
pesos =clf_Perceptron.coef_ 

In [8]:
type(pesos)

numpy.ndarray

In [9]:
pesos.shape

(1, 2)

In [10]:
pesos[0]

array([2., 2.])

vamos con otro ejemplo para consolidar conocimientos
https://www.interactivechaos.com/manual/tutorial-de-machine-learning/perceptron-multicapa

Las arquitecturas vistas hasta ahora (redes neuronales formadas por capas de neuronas, navegando los datos desde la capa de entrada hasta la capa de salida, etc.) se corresponden con lo que se denomina perceptrón multicapa. A pesar del nombre, esta arquitectura no está basada en perceptrones, simplemente se ha conservado el término "percentrón" en el nombre por motivos históricos.

Scikit-Learn implementa el perceptrón multicapa para clasificación y regresión en las clases sklearn.neural_network.MLPClassifier y sklearn.neural_network.MLPRegressor respectivamente.

Veamos un sencillo ejemplo. Supongamos que partimos del siguiente dataset:

In [11]:
import pandas as pd
import numpy as np
df = pd.DataFrame({
    "x0": [0.3, 0.1, 0.4, 0.5],
    "x1": [0.7, 0.2, 0.3, 0.8],
    "y": [1, 0, 0, 1]
})
df

x0   x1  y
0  0.3  0.7  1
1  0.1  0.2  0
2  0.4  0.3  0
3  0.5  0.8  1

En x0 y x1 tenemos las características predictivas y en y la variable objetivo, que vamos a considerar categórica para trabajar en un escenario de clasificación. Como es habitual, creamos los conjuntos con las características predictivas y la variable objetivo:

In [12]:
y_train = df.pop("y")
X_train = df

El objetivo es entrenar una red neuronal con una capa oculta de 2 neuronas. En Scikit-Learn las clases MLPClassifier y MLPRegressor reciben como primer argumento el parámetro hidden_layer_sizes, que controla la arquitectura de la red neuronal. Este argumento debe ser una tupla cuyos valores representen el número de neuronas artificiales en cada capa oculta. Así, (2, ) representaría una única capa oculta con 2 neuronas (la coma es necesaria para evitar confundir el "2" con un número entero), o (5, 3) representaría dos capas ocultas con 5 y 3 neuronas artificiales respectivamente. En todo caso, la implementación de Scikit-Learn incluye un par de detalles que debemos conocer:

La capa de entrada está formada por los valores que toman las características con las que se va a alimentar la red. Es decir, en esta capa de entrada no se va a aplicar ninguna función a los datos.
En regresión, la capa de salida está formada por una única neurona.
En clasificación, la capa de salida está formada por tantas neuronas como clases, excepto si se trata de clasificación binaria, en cuyo caso solo hay una neurona cuya función de activación determina la clase a devolver como predicción.
Es decir, la arquitectura de la red neuronal que vamos a crear es la siguiente:
[Imgur](https://imgur.com/yWnJm1X)



..donde:

x0 y x1 son la características homónimas para cada muestra que se haga pasar por la red
N0 y N1 son las dos neuronas que componen la capa oculta
S es la neurona que compone la capa de salida (una sola pues estamos trabajando en un entorno de clasificación binaria)
w00 es el peso por el que se va a multiplicar x0 en la entrada a la neurona N0
w01 es el peso por el que se va a multiplicar x0 en la entrada a la neurona N1
w10 es el peso por el que se va a multiplicar x1 en la entrada a la neurona N0
w11 es el peso por el que se va a multiplicar x1 en la entrada a la neurona N1
b0 es el bias a sumar a los valores de entrada ponderados de la neurona N0
b1 es el bias a sumar a los valores de entrada ponderados de la neurona N1
w20 es el peso por el que se va a multiplicar la salida de la neurona N0 en la entrada a la neurona de salida S
w21 es el peso por el que se va a multiplicar la salida de la neurona N1 en la entrada a la neurona de salida S
b2 es el bias a sumar a los valores de entrada ponderados de la neurona de salida N
En resumen, trabajaremos con 6 pesos (llamados coeficientes en Scikit-Learn) y tres valores (bias) a añadir a los valores de entrada ponderados de las neuronas (llamados interceptores en Scikit-Learn).

Importamos ahora la clase MLPClassifier, instanciamos el modelo y lo entrenamos:

In [13]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier((2, ), random_state = 0, learning_rate_init = 0.1, activation = "logistic")

Estamos creando el modelo con una tasa de aprendizaje de 0.1 (con tan pocas muestras en el conjunto de entrenamiento haría falta pasar los datos muchas veces por la red -muchas "epochs"- para conseguir que el algoritmo convergiese si utilizásemos la tasa de aprendizaje por defecto de 0.001). Especificamos también que como función de activación en la capa oculta se use la función logística.

In [14]:
model.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(2,), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=0, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [15]:
model.fit(X_train, y_train)

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(2,), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=0, shuffle=True, solver='adam', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

Del resumen devuelto por el modelo al ser entrenado vemos que, por defecto, se realiza un máximo de 200 iteraciones ("epochs") y el "solver" utilizado es adam.

Veamos cuál es la predicción del modelo para los mismos valores con los que se ha entrenado y su precisión media:

In [16]:
model.predict(X_train)

array([1, 0, 0, 1], dtype=int64)

In [17]:
model.score(X_train, y_train)

1.0

El modelo generado tiene dos atributos que nos dan acceso a los coeficientes y a los interceptores:

In [18]:
model.coefs_

[array([[-0.14736599, -1.15400831],
        [-7.83405221,  9.72328823]]),
 array([[-6.60705046],
        [ 6.00857268]])]

In [19]:
model.intercepts_

[array([ 3.89827002, -4.41150649]), array([0.20379602])]

El atributo coefs_ devuelve un array con tantos elementos como capas (excluyendo la de entrada que ya se ha comentado que no va a aplicar ninguna transformación), estando formado cada elemento por una matriz de coeficientes (de pesos). El atributo intercepts_ devuelve otro array en el que cada elemento contiene el vector de bias de la capa correspondiente.

Ahora podemos llevar estos valores a nuestro esquema con la arquitectura de la red neuronal que acabamos de crear:
<blockquote class="imgur-embed-pub" lang="en" data-id="h9gYbSn"><a href="https://imgur.com/h9gYbSn">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>


(se muestran en azul los coeficientes y en verde los bias).

Una vez entrenada la red, para realizar una predicción, por ejemplo para el valor (x0 = 0.8, x1 = 0.3), bastaría con hacer pasar dicho valor por la red, aplicándose las funciones vistas en cada nodo, hasta alcanzar la capa de salida. La neurona artificial de esta capa de salida (solo una en el caso de clasificación binaria) aplica una función sigmoidea (con independencia de la función de activación usada en el resto de la red) al dato que resulta de ponderar y sumar sus datos de entrada, convirtiendo dicho dato en una probabilidad y deduciendo, a partir de ella, la clase a asignar.

In [20]:
pesos=model.coefs_

In [21]:
print(pesos[0])

[[-0.14736599 -1.15400831]
 [-7.83405221  9.72328823]]


In [22]:
N=np.transpose(pesos[0])
print(N)

[[-0.14736599 -7.83405221]
 [-1.15400831  9.72328823]]


In [23]:
pesos[1]

array([[-6.60705046],
       [ 6.00857268]])

In [24]:
S=np.transpose(pesos[1])
print(S)

[[-6.60705046  6.00857268]]
